uint8 THRUSTER_CMD_OFF=1
uint8 THRUSTER_CMD_CHARGE=2
uint8 THRUSTER_CMD_DISCHARGE=3
uint8 THRUSTER_CMD_BOTH=4
uint8 THRUSTER_CMD_CHARGE_FAULT=5
uint8 THRUSTER_CMD_CHARGE_FAULT_W_DISCHARGE=6
uint8 command