# Per-pack
uint16 temperature # deg C
uint16 voltage # V
uint16 current
uint16 avgCurrent
uint16 maxError
uint16 relativeSOC # percent
uint16 absoluteSOC # percent
uint16 countCapacity # Remaining capacity in Amp*hours
uint16 fullCapacity # Predicted capacity when fully charged in Amp*hours
uint16 status
uint16 countCycle
uint16 capacityDesign
uint16 dateManufacture
uint16 serialNumber
uint16 maxCellVoltage
uint16 mid1CellVoltage
uint16 mid2CellVoltage
uint16 minCellVoltage

