# Per-pack
float32 temperature # deg C
float32 voltage # V
float32 current
float32 avgCurrent
uint16 maxError
float32 relativeSOC # percent
float32 absoluteSOC # percent
float32 countCapacity # Remaining capacity in Amp*hours
float32 fullCapacity # Predicted capacity when fully charged in Amp*hours
uint16 status
float32 countCycle
float32 capacityDesign
uint32 dateManufacture
uint16 serialNumber
float32 maxCellVoltage
float32 mid1CellVoltage
float32 mid2CellVoltage
float32 minCellVoltage

